version: "3.8"

services:
    mysql-TimeFutebol:
        image: mysql:8.3
        container_name: TimeFutebol-mysql-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: TimeFutebol
        volumes:
            - TimeFutebol-db-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    TimeFutebol-db-data:
